// <auto-generated/>
#pragma warning disable CS0618
using Immich.Admin.Auth;
using Immich.Admin.Maintenance;
using Immich.Admin.Notifications;
using Immich.Admin.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich.Admin
{
    /// <summary>
    /// Builds and executes requests for operations under \admin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdminRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::Immich.Admin.Auth.AuthRequestBuilder Auth
        {
            get => new global::Immich.Admin.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maintenance property</summary>
        public global::Immich.Admin.Maintenance.MaintenanceRequestBuilder Maintenance
        {
            get => new global::Immich.Admin.Maintenance.MaintenanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Immich.Admin.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Immich.Admin.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Immich.Admin.Users.UsersRequestBuilder Users
        {
            get => new global::Immich.Admin.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
