// <auto-generated/>
#pragma warning disable CS0618
using Immich.Activities;
using Immich.Admin;
using Immich.Albums;
using Immich.ApiKeys;
using Immich.Assets;
using Immich.Auth;
using Immich.Download;
using Immich.Duplicates;
using Immich.Faces;
using Immich.Jobs;
using Immich.Libraries;
using Immich.Map;
using Immich.Memories;
using Immich.Notifications;
using Immich.Oauth;
using Immich.Partners;
using Immich.People;
using Immich.Plugins;
using Immich.Queues;
using Immich.Search;
using Immich.Server;
using Immich.Sessions;
using Immich.SharedLinks;
using Immich.Stacks;
using Immich.Sync;
using Immich.SystemConfig;
using Immich.SystemMetadata;
using Immich.Tags;
using Immich.Timeline;
using Immich.Trash;
using Immich.Users;
using Immich.View;
using Immich.Workflows;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImmichClient : BaseRequestBuilder
    {
        /// <summary>The activities property</summary>
        public global::Immich.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::Immich.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The admin property</summary>
        public global::Immich.Admin.AdminRequestBuilder Admin
        {
            get => new global::Immich.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The albums property</summary>
        public global::Immich.Albums.AlbumsRequestBuilder Albums
        {
            get => new global::Immich.Albums.AlbumsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apiKeys property</summary>
        public global::Immich.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::Immich.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::Immich.Assets.AssetsRequestBuilder Assets
        {
            get => new global::Immich.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Immich.Auth.AuthRequestBuilder Auth
        {
            get => new global::Immich.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::Immich.Download.DownloadRequestBuilder Download
        {
            get => new global::Immich.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The duplicates property</summary>
        public global::Immich.Duplicates.DuplicatesRequestBuilder Duplicates
        {
            get => new global::Immich.Duplicates.DuplicatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The faces property</summary>
        public global::Immich.Faces.FacesRequestBuilder Faces
        {
            get => new global::Immich.Faces.FacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Immich.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Immich.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The libraries property</summary>
        public global::Immich.Libraries.LibrariesRequestBuilder Libraries
        {
            get => new global::Immich.Libraries.LibrariesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The map property</summary>
        public global::Immich.Map.MapRequestBuilder Map
        {
            get => new global::Immich.Map.MapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memories property</summary>
        public global::Immich.Memories.MemoriesRequestBuilder Memories
        {
            get => new global::Immich.Memories.MemoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Immich.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Immich.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Immich.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Immich.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partners property</summary>
        public global::Immich.Partners.PartnersRequestBuilder Partners
        {
            get => new global::Immich.Partners.PartnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The people property</summary>
        public global::Immich.People.PeopleRequestBuilder People
        {
            get => new global::Immich.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugins property</summary>
        public global::Immich.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::Immich.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queues property</summary>
        public global::Immich.Queues.QueuesRequestBuilder Queues
        {
            get => new global::Immich.Queues.QueuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Immich.Search.SearchRequestBuilder Search
        {
            get => new global::Immich.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The server property</summary>
        public global::Immich.Server.ServerRequestBuilder Server
        {
            get => new global::Immich.Server.ServerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Immich.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Immich.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sharedLinks property</summary>
        public global::Immich.SharedLinks.SharedLinksRequestBuilder SharedLinks
        {
            get => new global::Immich.SharedLinks.SharedLinksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stacks property</summary>
        public global::Immich.Stacks.StacksRequestBuilder Stacks
        {
            get => new global::Immich.Stacks.StacksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::Immich.Sync.SyncRequestBuilder Sync
        {
            get => new global::Immich.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The systemConfig property</summary>
        public global::Immich.SystemConfig.SystemConfigRequestBuilder SystemConfig
        {
            get => new global::Immich.SystemConfig.SystemConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The systemMetadata property</summary>
        public global::Immich.SystemMetadata.SystemMetadataRequestBuilder SystemMetadata
        {
            get => new global::Immich.SystemMetadata.SystemMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Immich.Tags.TagsRequestBuilder Tags
        {
            get => new global::Immich.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timeline property</summary>
        public global::Immich.Timeline.TimelineRequestBuilder Timeline
        {
            get => new global::Immich.Timeline.TimelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trash property</summary>
        public global::Immich.Trash.TrashRequestBuilder Trash
        {
            get => new global::Immich.Trash.TrashRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Immich.Users.UsersRequestBuilder Users
        {
            get => new global::Immich.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The view property</summary>
        public global::Immich.View.ViewRequestBuilder View
        {
            get => new global::Immich.View.ViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Immich.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Immich.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.ImmichClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImmichClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "/api";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
