// <auto-generated/>
#pragma warning disable CS0618
using Immich.Auth.AdminSignUp;
using Immich.Auth.ChangePassword;
using Immich.Auth.Login;
using Immich.Auth.Logout;
using Immich.Auth.PinCode;
using Immich.Auth.Session;
using Immich.Auth.Status;
using Immich.Auth.ValidateToken;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The adminSignUp property</summary>
        public global::Immich.Auth.AdminSignUp.AdminSignUpRequestBuilder AdminSignUp
        {
            get => new global::Immich.Auth.AdminSignUp.AdminSignUpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changePassword property</summary>
        public global::Immich.Auth.ChangePassword.ChangePasswordRequestBuilder ChangePassword
        {
            get => new global::Immich.Auth.ChangePassword.ChangePasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::Immich.Auth.Login.LoginRequestBuilder Login
        {
            get => new global::Immich.Auth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::Immich.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::Immich.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pinCode property</summary>
        public global::Immich.Auth.PinCode.PinCodeRequestBuilder PinCode
        {
            get => new global::Immich.Auth.PinCode.PinCodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The session property</summary>
        public global::Immich.Auth.Session.SessionRequestBuilder Session
        {
            get => new global::Immich.Auth.Session.SessionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Immich.Auth.Status.StatusRequestBuilder Status
        {
            get => new global::Immich.Auth.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validateToken property</summary>
        public global::Immich.Auth.ValidateToken.ValidateTokenRequestBuilder ValidateToken
        {
            get => new global::Immich.Auth.ValidateToken.ValidateTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
