// <auto-generated/>
#pragma warning disable CS0618
using Immich.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Immich.Memories.Statistics
{
    /// <summary>
    /// Builds and executes requests for operations under \memories\statistics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatisticsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Memories.Statistics.StatisticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatisticsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/memories/statistics{?for*,isSaved*,isTrashed*,order*,size*,type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Memories.Statistics.StatisticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatisticsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/memories/statistics{?for*,isSaved*,isTrashed*,order*,size*,type*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve statistics about memories, such as total count and other relevant metrics.
        /// </summary>
        /// <returns>A <see cref="global::Immich.Models.MemoryStatisticsResponseDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Immich.Models.MemoryStatisticsResponseDto?> GetAsync(Action<RequestConfiguration<global::Immich.Memories.Statistics.StatisticsRequestBuilder.StatisticsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Immich.Models.MemoryStatisticsResponseDto> GetAsync(Action<RequestConfiguration<global::Immich.Memories.Statistics.StatisticsRequestBuilder.StatisticsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Immich.Models.MemoryStatisticsResponseDto>(requestInfo, global::Immich.Models.MemoryStatisticsResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve statistics about memories, such as total count and other relevant metrics.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Immich.Memories.Statistics.StatisticsRequestBuilder.StatisticsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Immich.Memories.Statistics.StatisticsRequestBuilder.StatisticsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Immich.Memories.Statistics.StatisticsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Immich.Memories.Statistics.StatisticsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Immich.Memories.Statistics.StatisticsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve statistics about memories, such as total count and other relevant metrics.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StatisticsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("for")]
            public DateTimeOffset? For { get; set; }
            [QueryParameter("isSaved")]
            public bool? IsSaved { get; set; }
            [QueryParameter("isTrashed")]
            public bool? IsTrashed { get; set; }
            [QueryParameter("order")]
            public global::Immich.Models.MemorySearchOrder? Order { get; set; }
            /// <summary>Number of memories to return</summary>
            [QueryParameter("size")]
            public int? Size { get; set; }
            [QueryParameter("type")]
            public global::Immich.Models.MemoryType? Type { get; set; }
        }
    }
}
#pragma warning restore CS0618
