// <auto-generated/>
#pragma warning disable CS0618
using Immich.Trash.Empty;
using Immich.Trash.Restore;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich.Trash
{
    /// <summary>
    /// Builds and executes requests for operations under \trash
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrashRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The empty property</summary>
        public global::Immich.Trash.Empty.EmptyRequestBuilder Empty
        {
            get => new global::Immich.Trash.Empty.EmptyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::Immich.Trash.Restore.RestoreRequestBuilder Restore
        {
            get => new global::Immich.Trash.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Trash.TrashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrashRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/trash", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Trash.TrashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrashRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/trash", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
