// <auto-generated/>
#pragma warning disable CS0618
using Immich.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Immich.Map.Markers
{
    /// <summary>
    /// Builds and executes requests for operations under \map\markers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MarkersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Map.Markers.MarkersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarkersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map/markers{?fileCreatedAfter*,fileCreatedBefore*,isArchived*,isFavorite*,withPartners*,withSharedAlbums*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Map.Markers.MarkersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarkersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map/markers{?fileCreatedAfter*,fileCreatedBefore*,isArchived*,isFavorite*,withPartners*,withSharedAlbums*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a list of latitude and longitude coordinates for every asset with location data.
        /// </summary>
        /// <returns>A List&lt;global::Immich.Models.MapMarkerResponseDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Immich.Models.MapMarkerResponseDto>?> GetAsync(Action<RequestConfiguration<global::Immich.Map.Markers.MarkersRequestBuilder.MarkersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Immich.Models.MapMarkerResponseDto>> GetAsync(Action<RequestConfiguration<global::Immich.Map.Markers.MarkersRequestBuilder.MarkersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Immich.Models.MapMarkerResponseDto>(requestInfo, global::Immich.Models.MapMarkerResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Retrieve a list of latitude and longitude coordinates for every asset with location data.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Immich.Map.Markers.MarkersRequestBuilder.MarkersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Immich.Map.Markers.MarkersRequestBuilder.MarkersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Immich.Map.Markers.MarkersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Immich.Map.Markers.MarkersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Immich.Map.Markers.MarkersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a list of latitude and longitude coordinates for every asset with location data.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MarkersRequestBuilderGetQueryParameters 
        {
            [QueryParameter("fileCreatedAfter")]
            public DateTimeOffset? FileCreatedAfter { get; set; }
            [QueryParameter("fileCreatedBefore")]
            public DateTimeOffset? FileCreatedBefore { get; set; }
            [QueryParameter("isArchived")]
            public bool? IsArchived { get; set; }
            [QueryParameter("isFavorite")]
            public bool? IsFavorite { get; set; }
            [QueryParameter("withPartners")]
            public bool? WithPartners { get; set; }
            [QueryParameter("withSharedAlbums")]
            public bool? WithSharedAlbums { get; set; }
        }
    }
}
#pragma warning restore CS0618
