// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Immich.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MaintenanceAction
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "start")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "end")]
        #pragma warning disable CS1591
        End,
        #pragma warning restore CS1591
    }
}
