// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Immich.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PluginContext
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "asset")]
        #pragma warning disable CS1591
        Asset,
        #pragma warning restore CS1591
        [EnumMember(Value = "album")]
        #pragma warning disable CS1591
        Album,
        #pragma warning restore CS1591
        [EnumMember(Value = "person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
    }
}
